### ISSUE TITLE
FYI: react-native-windows

### ISSUE THREAD

**Issue by PPatBoyd** [colinhartigan/valorant-skin-manager#1]
https://github.com/Microsoft/react-native-windows

Worth checking out since windows is the target platform. If it has blocking issues LMK I'd be interested to hear e.g. if it can't connect to the Valorant API -- I contribute to the repo occasionally.

It also has a package for react-native-win32 but that's relatively bespoke and not intended for general use atm

**Comment by colinhartigan** [comment]
I'll definitely keep this in mind going forward for both this and future projects - I've gotten pretty far into development with VSM in ReactJS and would like to have a completely working version (especially for figuring out the backend because I could reuse it) before looking into porting it to react-native

**Comment by colinhartigan** [comment]
I've ended up hosting the frontend on github pages as static HTML and the websocket server runs locally. This will (should) reduce the download size and overall heft of the app.
